# Coder Plugin Configuration
plugin:
  enabled: true

# Script Settings
scripts:
  python-enabled: true
  lua-enabled: true
  java-enabled: true

# Enable Coder Addons?
enabled: true
blocked-addon-message: "[Coder] This Coder Addon Has Been Blocked. If This is a mistake please read your code."