name: CodeDSL
version: 1.8.2
main: me.coder.codedsl.CodeDSLPlugin
description: A Domain Specific Language addon for the Coder plugin
author: Firesmasher
api-version: '1.21'

dependencies:
  server:
    Coder:
      load: BEFORE
      required: true

commands:
  codedsl:
    description: Execute and manage CodeDSL scripts
    usage: /codedsl <run|reload|load|unload|list> <filename>
    aliases:
      - cdsl
      - code-dsl

permissions:
  codedsl.use:
    description: Allows usage of CodeDSL commands
    default: op
  codedsl.command:
    description: Allows running CodeDSL commands
    default: op